[theme]
primaryColor="#32b371"
backgroundColor="#2f2e2e"
secondaryBackgroundColor="#777777"
textColor="#ffffff"


[[pages]]
path = "app.py"
name = "Inicio"
icon = ""

[[pages]]
path = "views/datos.py"
name = "Analisis"
icon = "📉"

[[pages]]
path = "views/beta.py"
name = "beta"
icon = ""

[[pages]]
path = "views/reportes.py"
name = "Reportes"
icon = ""
